# Generated by Django 2.2.11 on 2020-03-10 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action_Blueprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_blueprint', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Become_Educated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('become_educated', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='BigIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_issue', models.PositiveSmallIntegerField(choices=[(1, 'Poverty'), (2, 'Hunger'), (3, 'Health'), (4, 'Education'), (5, 'Gender Equality'), (6, 'Refugees'), (7, 'Water'), (8, 'Energy'), (9, 'Labor'), (10, 'Inequality'), (11, 'Sustainability'), (12, 'Consumption'), (13, 'Climate'), (14, 'Conservation'), (15, 'Conflict')], default=1)),
                ('become_educated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp_1.Become_Educated')),
            ],
        ),
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('level', models.IntegerField()),
                ('team_logo', models.FileField(upload_to='')),
                ('accepting_members', models.BooleanField(default=True)),
                ('numMembers', models.IntegerField(default=0)),
            ],
            options={
                'permissions': (('create_team', 'Create a Team'), ('join_team', 'Join Team')),
            },
        ),
        migrations.CreateModel(
            name='TeamProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp_1.Team', verbose_name='Team')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_type', models.PositiveSmallIntegerField(choices=[(1, 'Community Objective'), (2, 'Fundraising'), (3, 'Awareness & Analysis')], default=1)),
                ('action_blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp_1.Action_Blueprint')),
                ('impact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp_1.Impact')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp_1.Solution')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionPassion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_passion', models.PositiveSmallIntegerField(choices=[(1, 'Music'), (2, 'Art'), (3, 'Sports'), (4, 'Coding'), (5, 'Baking'), (6, 'Speaking')], default=1)),
                ('action_blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp_1.Action_Blueprint')),
                ('impact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp_1.Impact')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp_1.Solution')),
            ],
        ),
        migrations.AddField(
            model_name='solution',
            name='team_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp_1.TeamProfile'),
        ),
        migrations.CreateModel(
            name='RootCause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('big_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp_1.BigIssue')),
                ('root_cause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp_1.RootCause')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=30)),
                ('team_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp_1.TeamProfile')),
            ],
        ),
        migrations.AddField(
            model_name='impact',
            name='team_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp_1.TeamProfile'),
        ),
        migrations.AddField(
            model_name='bigissue',
            name='impact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp_1.Impact'),
        ),
        migrations.AddField(
            model_name='bigissue',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp_1.Problem'),
        ),
        migrations.AddField(
            model_name='become_educated',
            name='team_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp_1.TeamProfile'),
        ),
        migrations.AddField(
            model_name='action_blueprint',
            name='team_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp_1.TeamProfile'),
        ),
    ]
